# Since many packages don't provide musl wheels, use debian base image. Also simplifies managing uv.lock.
# Avoids issues like: https://github.com/home-assistant/wheels-custom-integrations/pull/696
# TODO: figure out how to use alpine base image in the future.
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bookworm"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bookworm"