name: "Home Agent"
version: "1.0.0"
slug: "home-agent"
init: false
description: "AI agent for Home Assistant"
url: "https://github.com/taha-yassine/home-agent"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
homeassistant_api: true
ports:
  8000/tcp: 8000
ingress: true
ingress_port: 8000
panel_icon: mdi:robot-happy
panel_title: Home Agent
